---
title: "Film Studies Piece"
format: html
editor: visual
---

#### In Seeing the Light: *Tangled* and the Romantic Comedy for Children, I explore the parallels found between the Disney movie *Tangled* (2010) and the romantic comedy tradition, arguing that in defining *Tangled* as a rom-com, the film ultimately warps the perceptions and expectations of romance toward children to be in line with a heteronormative convention.

## Seeing the Light: Tangled and the Romantic Comedy for Children

The scene opens up to a boy and a girl standing in front of one another, finding love in one another's eyes and in the experiences they have shared. Could it be in the aftermath of parent meddling as seen in Ol Parker's *Ticket to Paradise* (2022) when Georgia Cotton (Julia Roberts) and David Cotton (George Clooney) decide to destroy the budding relationship of their daughter and her fiancé? Or following an almost relationship-ending miscommunication the likes Andie Anderson (Kate Hudson) and Benjamin Barry (Matthew McConaughey) faced in Donald Petrie's *How to Lose a Guy in 10 Days* (2003)? Maybe it was after a thrilling adventure that brought the pair closer like what was produced with Fred Flarsky (Seth Rogen) and Charlotte Field (Charlize Theron) in Jonathan Levine's *Long Shot* (2019). Or was that the plot of Frank Capra's *It Happened One Night* (1934)? Did *How to Lose a Guy in 10 Days* just perpetuate the bets and masquerade introduced in *She's All That* (1999)? Was *Ticket to Paradise* competing with its predecessor, *Monster-in-Law* (2005), for the worst in-law award? With romantic comedies dating back to the as early as the 1920s, it's no wonder that the same tropes would appear time and time again, generation to generation. However, no matter the romantic comedy, as Claire Mortimer describes in her piece Romantic Comedy, the heroine inevitably "embraces the romantic dream and is whisked oﬀ her feet by the right guy, having realized that love conquers all" (30). A romantic comedy can always guarantee the happily ever after, as if it was written in a fairy tale---and in some cases they are.

Encapsulating the themes and storylines from *Ticket to Paradise* to *It Happened One Night*, Disney's *Tangled* (2010), directed by Nathan Greno and Byron Howard, follows the story of Rapunzel (Mandy Moore) and Flynn Rider (Zachary Levi) as they embark on a journey to the kingdom of Corona to see the "floating lanterns". For the entirety of Rapunzel's life, she has been locked away in a tower by Mother Gothel (Donna Murphy), a woman who kidnapped her from her parents, the king and queen of Corona, in order to use her for her magical, healing hair. She forbids Rapunzel to leave the tower and venture out into what she claims to be a dangerous world, until she meets Flynn Rider, a thief on the run after stealing the crown of the lost princess of Corona. With Flynn, she finally ventures out into the world, encountering misunderstood ruffians, a rule-following palace horse, and vengeful brothers. Rapunzel and Flynn grow closer and closer, until Mother Gothel drives them apart by capturing Rapunzel and getting Flynn arrested. Flynn ultimately escapes prison and tries to free Rapunzel but is stabbed by Mother Gothel. Rapunzel makes a deal to heal Flynn, but as she does he cuts her hair, and therefore Mother Gothel's lifeline, dying in the process. Filled with love and grief for him, Rapunzel's teardrops bring him back to life and they go on to reunite her with her family and the pair live happily ever after. In further exploring the parallels found between *Tangled* and the romantic comedy tradition, I will argue that the film's definition as a rom-com ultimately warps the perceptions and expectations of romance toward children to be in line with a heteronormative convention.

*Tangled* received a generally positive critical response from both the audience and critics alike. Rotten Tomatoes gave the film an eighty-nine percent from over two hundred reviews, with the audience giving it an eighty-seven percent. Similarly, Cinemascore scored the film at an A+ on their scale. The website Metacritic, though slightly more critical, rated the film positively at seventy-one percent. The praise *Tangled* received extended to the responses from film critics across various publications following its release.

Critics, as with any Disney film, look closely at the innovation and storytelling told within each film---*Tangled* is no exception, and the positive reception it received underscores just that. The film received extensive praise for its traditional elements while introducing modern storytelling, with New York Times critic A.O Scott saying it is "a lavish, romantic musical fairy tale" and that "its look and spirit convey a modified, updated but nonetheless sincere and unmistakable quality of old-fashioned Disneyness." A critic from Time, Richard Corliss, expanded on this by describing the film as having a "complex mix of romance, comedy, adventure and heart." The genuine storytelling and lightheartedness was a poignant detail emphasized by many critics, including Kenneth Turan who claims that "when *Tangled*'s core sweetness asserts itself and the film dares to wear its heart on its sleeve in a climactic scene featuring 46,000 paper lanterns, it's been worth the wait." NBC News critic Gael Cooper shared a similar, positive sentiment, praising the film for its "modern, witty edge" and boldly asserting that it may be Disney's best film yet.

Despite the overwhelming praise from audience members and critics, film critics from websites such as ReelViews and the Hollywood Reporter viewed the film as more lackluster and less groundbreaking than other critics depicted. Todd McCarthy from the Hollywood Reporter was among those who were left unimpressed by Disney's 50th anniversary film, describing the film as "a passably entertaining hodgepodge of old and new animation techniques, mixed sensibilities and hedged commercial calculations." A ReelViews review from James Berardinelli gave the film three stars out of five and criticized it for occupying "a plateau below the one where the best animated Disney movies reside." Berardinelli went on to remark that the music was "neither catchy nor memorable" and that "Rapunzel, although likable and energetic, is not as memorable as Snow White, Ariel, or Belle."

Although *Tangled* does not have extensive scholarship, scholars such as Magnussen and Stephens, have delved into the different ways it has dealt with previous themes portrayed in the typical princess film. In Kendra Magnussen's piece for Marvels & Tales, she expands on the symbolism of Rapunzel's hair transformation as being indicative of a transfer from a mother-daughter relationship to a romantic relationship. Magnussen argues that "although the film maintains themes related to coming of age, it strategically avoids other versions' sexual implications of young womanhood while vilifying mature femininity and invalidating nonbiological mothering." Jena Stephens, in her piece "Disney's Darlings: An Analysis of The Princess and the Frog, Tangled, Brave and The Changing Characterization of the Princess Archetype," also touches on the modern themes exhibited in *Tangled* but through Rapunzel's characterization. Stephens explains that throughout the film, Rapunzel "differs significantly from the first generation of Disney princesses who not only lacked rebellious qualities, but were insufferably agreeable, even if it meant performing ridiculous tasks, such as Cinderella becoming a handmaiden for her step mother and two step sisters." The broadened thematic qualities that *Tangled* displays allow for the film to be discussed and compared to not only its predecessors but to different genres that aid in best describing the film as a whole.

In entertaining traditional issues of parental to lover relationships and its position alongside previous Disney princess portrayals, *Tangled* continues to expand the ideas of a princess movie by exhibiting a transcendent quality that is reminiscent of films found within the romantic comedy genre. Although Magnussen and Stephens acknowledge the lengths *Tangled* has reached in widening the conversation and of the modern, princess story, they neglect to find the similarities that *Tangled* shares with romantic comedy films that define the film and its intentions with greater efficacy. This idea is introduced in Caroline Siede's article "10 Years Ago, Tangled Reinvigorated the Disney Princess Tradition," where she uses the comparison of Rapunzel and Flynn Rider's relationship progression to the one found in *When Harry Met Sally* (1989). With this, Siede draws on the parallels of previous rom-coms to describe Rapunzel's "mix of naive, neurotic weirdness and openhearted kindness" to Elle Woods in *Legally Blonde* (2001) and argues that "while most Disney princess films feature some sort of romance, *Tangled* is the most overtly rom-com-y of the bunch, with equal focus given to both of its leads and a certain effervescence to their dynamic." In displaying yet another example of a heterosexual coupling, *Tangled* demonstrates an application of the conventions and formula of the romantic comedy genre to a film targeted at a much younger audience in order to further reinforce the notion of heteronormativity.

In Tamar Jeffers McDonald's genre-defining book Romantic Comedy: Boy Meets Girl Meets Genre, she posits that a romantic comedy is inherently a story where "its central narrative motor a quest for love, which portrays this quest in a light-hearted way and almost always to a successful conclusion" (9). McDonald's argument stems from the relationship between romantic comedies and the visual and narrative traditions they all share, such as tropes and genre clichés (11). Despite admitting that the romantic comedy genre is often viewed as a "guilty pleasure," she combats the simplification of the rom-com by commenting on the wider ideology of romantic comedies as one centered around the relationship that undeniably evokes an emotional response from the audience (13). She expands on this idea by positioning romantic comedies as conventionally "providing fairy tales for adults" (12) through the use of repetitive narrative patterns such as the 'meet-cute' (17). In the evolution of the rom-com into a neotraditional age, McDonald notes the continuity of the "boy meets, loses, regains girl structure" while keeping in a typically heterosexual portrayal (86).

In line with other films in the Disney catalog, *Tangled* is an inherently comedic film that introduces romance as the attractive conclusion. The animal characters of the film, specifically Maximus the palace horse and Pascal, and their personified facial expressions lend to the comedic aspects that help distinguish the romantic comedy from simply a romantic drama. The altercations and interactions between Flynn and Pascal---as Pascal sticks his tongue in Flynn's ear to wake him---and Flynn and Maximus---as shown through their adolescent feud throughout the film---illustrate a slapstick, physical comedy that is reminiscent of rom-coms from the early, screwball era described by McDonald. By establishing the comedic center of the film early on, it allows for the romantic, narrative arc to develop.

The formulaic elements that make up the storyline of most, if not all, romantic comedies are demonstrated in *Tangled* through one of its opening scenes. Such as the case in romantic comedies before it, the film introduces the heroine in a scene where Rapunzel converses with her chameleon pet, Pascal, and goes about her daily routine. In her early interactions with Pascal, we see the chameleon encourage Rapunzel to leave the tower, to which Rapunzel replies with "I like it in here, and so do you." However, as she sings along to the track "When Will My Life Begin," we see Rapunzel recount each of the tasks---some as absurd as ventriloquy and pottery making to some monotonous ones such as brushing her hair and cleaning---that make up her day within the tower. The wishful lyrics of the song, coupled with the various ways in which Rapunzel keeps herself occupied and distracted, illustrate the restlessness of a heroine longing to pursue her dream, but fearful and waiting for someone, such as a man, to start her own adventure. Although she exhibits an independence and curiosity not known by previous Disney princesses, Rapunzel continues to make her characterization more in line with that seen in McDonald's description of neo-traditional romantic comedies where the heroine is reactionary to her fate while displaying a shallow empowerment in her character by waiting for a male figure like Flynn Rider to come along and helps Rapunzel answer the question she continuously sings, "when will my life begin?"

The similarities between *Tangled* and the narrative arc described by McDonald is reinforced in the 'meet-cute' between Rapunzel and Flynn Rider. Flynn climbs Rapunzel's tower to flee from the palace guards of Corona after stealing the crown of the lost princess of Corona, only to get knocked out by Rapunzel's frying pan. After Flynn awakens with help from a comedic display by Pascal, Rapunzel introduces herself from the shadows, accentuating the conventionally attractive features of her blonde hair and large green eyes. The scene proceeds to shift to Flynn's reaction, where his gaping mouth and wide eyes exhibit a shock toward her beauty, a standard reaction to demonstrate attraction to the intended heteronormative audience. The degree to which the film makes a spectacle of their first encounter reinforces that it is a 'meet-cute' as the deal they ultimately make for Rapunzel to travel to see the lanterns foreshadows the foundation of the relationship they will build on their journey that aligns with McDonald's perception that a 'meet-cute' serves to "forecast their eventual union" (12).

In line with a romantic comedy, the relationship between Rapunzel and Flynn grows through moments of vulnerability and shared experiences. After surviving an encounter with Flynn's vengeful, estranged partners, the Stabbington brothers, and palace guards, Rapunzel and Flynn find themselves trapped in a flooding cave. Facing impending death, Flynn reveals that his name is actually Eugene Fitzherbert and Rapunzel confesses the magical abilities her hair possesses. The pair continue to share their vulnerabilities and backstories in a campfire after escaping the cave, growing closer as the scene closes in on their caring, almost flirtatious expressions toward each other until Flynn nervously clears his throat. A central ideology expressed within romantic comedies is not only that the story sees two people fall in love but that they both change in one way or another. At the beginning of the film, Flynn is posed as a sly thief who puts his needs above anyone else. He expresses such when he cleverly abandons the Stabbington brothers (Ron Perlman) as they escape Corona and describes being "surrounded by enormous piles of money" as his dream when Rapunzel sings "I've Got A Dream" with the unruly members of the Snuggly Duckling. In their conversation around the campfire, however, Flynn is sharing a vulnerable part of his identity with Rapunzel, establishing trust within the pair that is reminiscent of a scene in another romantic comedy---*Long Shot*---where the characters create a more intimate bond following a near-death experience. The character arc of Flynn becoming a more sensitive, loyal figure and Rapunzel into a more independent thinking woman is a trait of the romantic comedy genre that is undeniably present in *Tangled* that exploits their growth as a vehicle to grow closer as a couple.

The light-hearted romance continues to build when the pair release lanterns together on the water on the evening of Rapunzel's birthday, capturing the emotional and romantic essence of a romantic comedy. The setting is quite intimate and romantic, with the only light coming from the lanterns in the kingdom and the frame focusing on the warm hues coming off of Rapunzel and Flynn. The scene rotates between close-ups of Rapunzel and Flynn looking at each other as they sit there taking in the magical scene of the lanterns. The song in this scene, as is the case throughout this musical film, plays an important role in moving the plot as it helps to illustrate their realization that their new ambitions lie in pursuing the love they have for one another. The emotion demonstrated in this scene---through the setting, soundtrack, and facial expressions---is ultimately the goal of the romantic comedy, as the emotional response evoked from the audience is the greatest ideological principle of the rom-com. This occasion puts the development of romance at the forefront of this film, separating itself from princess films prior through the intentional evolution of their relationship.

Interrupting the romantic elements and slapstick comedy of the film is a parental relationship that serves as the catalyst for the "boy loses girl" portion of the film. Throughout the film, Mother Gothel exploits Rapunzel for her naivete, continuously warding her against exploring the world outside her tower for the dangers that lie outside of it. In this case, Mother Gothel enlists the help of the Stabbington brothers to make Rapunzel think that Flynn ran away with the stolen crown when in fact he was ambushed by the brothers and propped up to appear as if he was sailing a ship despite being unconscious. The ship sails back toward Corona and gets Flynn captured by the palace guards. Distraught, Rapunzel falls back into Mother Gothel's arms and follows her back to the tower. The trope of the "misunderstanding" scene, or the moment in a rom-com where the pair is thrust apart as a result of a misunderstanding or lack of communication between the two of them, is a clear exemplification of the romantic comedy genre exploited in the film. With this, the parent meddling in the relationship in a rom-com is another widely presented trope as seen in *Ticket to Paradise* or *Monster-in-Law*. Although arguably the mother-daughter relationship presented in *Tangled* is more problematic and manipulative than the love shown in those films, the pair's conflict is spurred through Mother Gothel's actions, thus reinforcing the narrative elements and cliches found not only within most romantic comedies but in *Tangled* as well.

Emotion and curating a future built on love is ultimately the message *Tangled* imparts, placing it amongst other great romantic comedies. McDonald described that pain and loss is a core theme to the rom-com, arguing that "crying frequently occupies an important space in the narratives of the romantic comedy: as an index of the pain a lover feels when apart from the beloved" (10). At the climax of the film, we see Flynn climb up the tower once more, only to find Rapunzel trapped by Mother Gothel. Flynn immediately gets stabbed by Mother Gothel, sustaining a life-threatening injury. In exchange for healing him, Rapunzel offers to go away with Mother Gothel, and she hesitantly agrees. As Rapunzel rushes to save Flynn's life, he decides to cut off her hair before she can heal him and spend the rest of her life with Mother Gothel, instantly turning Mother Gothel to dust as the age catches up with her. In his dying moments, Flynn tells Rapunzel that "you were my new dream" to which Rapunzel replies "and you were mine." This scene, though explicitly emotional in intention and presentation, exploits the ideas of romance becoming the desired life path for both men and women that reinforces the ideologies in a rom-com that in order for men and women to be fulfilled they must find love. Rapunzel eventually heals Flynn through a magic-containing teardrop and they get the happily ever after the rom-com promises, but in doing so it once again presents the narrative that love is the only acceptable plan after pursuing one's individual pursuits.

In viewing *Tangled* as a rom-com that perpetuates the ideas of love and the "happy ending" found in the neo-traditional romantic comedy, there are dangerous ramifications that inevitably impacts the socialization of children to romantic relationships, specifically toward heteronormativity. In their piece "Hetero-Romantic Love and Heterosexiness in Children's G-Rated Films," Karin Martin and Emily Kazyak assert that since the media has been found to be a crucial part of their development and socialization, animated films targeted toward children or a general audience "provide powerful portraits of a multifaceted and pervasive heterosexuality that likely facilitates the reproduction of heteronormativity" (333). The pair stress that as more children's films display heterosexual relationships, the social structure of heteronormativity as the "favored" or "expected" will only continue to be exploited and "marginalizes those outside of it" (316). Research by Rana Sultan and Farid Bin Masood in their paper "Portrayals of Love, Romance & Sexuality in Animated Films for Children: A Content Analysis of Animated Films Released in 2018" underscores the accentuation of romance toward children, as they found that out of the 16 animated films they analyzed, 25% were categorized as romantic and 62.5% had any reference to marriage (5). Arguably their most alarming conclusion, however, was that their data supported the trend that female characters are "more likely to be cast in a leading role when the central plot includes themes of romance, family, or sexuality, and more likely to be married or attached to a significant other by the end of the film" (6).

*Tangled'*s emphasis on the pursuit of love and a romantic relationship preserves the problematic tradition of heteronormativity in the media. The narrative arc that the film follows is in line with not only the formulaic properties of the romantic comedy genre but also the tropes within the princess genre that it attempts to stray away from. In another fairytale adaptation by Disney, *Beauty and the Beast* (1991), Belle (Paige O'Hara) is depicted as a strong-willed, independent woman who gets imprisoned in a castle by the Beast (Robby Benson) and eventually falls in love with him through the connection and intimacy they develop throughout the film, from romantic dance scenes to displays of affection in the form of gifts or self-sacrifice. Generations prior, Disney's *Cinderella* (1950) depicts a hardworking, faithful girl (Ilene Woods) that eventually escapes the tortuous demands of her stepmother and stepsisters by falling in love with Prince Charming (William Edward Phipps). The movies all end the same way---the boy always ends up with the girl.

*Tangled* claims to be a film that transcends the princess genre, but ultimately it promotes the same message to children, generation after generation, regardless of its classification. Although romantic comedies are often recognized for their harmless, unrealistic portrayals of love, the depiction of these traditions within the avenue of children's and animated films have the potential to continue a cycle of heteronormativity that warps the socialization of children to the much wider scope of relationships that lie outside of them. Children who identify as anything but heterosexual will never know acceptance in a society where animated films like Tangled continue to perpetuate solely heteronormative relationships on the screen. Disney has looked to promote a reimagined take on their antiquated stories, such as casting Halle Bailey, a Black actress, as Ariel in the live action remake of *The Little Mermaid* (2023). In doing so, they have introduced young girls to the idea of Ariel as a character who can look like them, resulting in praise and joyous reactions from the audience preceding the release of the film (Cannella). This progress they have made in presenting greater racial representation must also extend to the types of relationships they display on the screen and the consequences that can have on our children. Romantic comedies as magical and impactful as Tangled have a responsibility to its audiences, from children to adults, to push the romantic comedy past its "boy meets girl" formula.

### Works Cited 

-   Beauty and the Beast. Directed by Gary Trousdale and Kirk Wise, performances by Paige O'Hara and Robby Benson, Walt Disney Studios Motion Pictures, 1991.

-   Berardinelli, James. "Tangled (United States, 2010)." Reelviews Movie Reviews, 24 Nov. 2010, https://www.reelviews.net/reelviews/tangled.

-   Cannella, Greg. "'She's Brown like Me': Young Girls React to Halle Bailey as Ariel in Disney's 'The Little Mermaid.'" CBS News, 13 Sept. 2022, https://www.cbsnews.com/news/halle-bailey-ariel-the-little-mermaid-black-girls-react-to-trailer/.

-   Cinderella. Directed by Clyde Geronimi, Wilfred Jackson, and Hamilton Luske, performances by Ilene Woods and William Edward Phipps, Walt Disney Studios Motion Pictures, 1950.

-   Cooper, Gael Fashingbauer. "'Tangled' May Be Best Disney Movie of All Time." NBCNews, 13 Jan. 2012, https://www.nbcnews.com/pop-culture/pop-culture-news/tangled-may-be-best-disney-movie-all-time-flna6c9593389.

-   Corliss, Richard. "Tangled: Disney's Ripping Rapunzel." Time Inc., 26 Nov. 2010, https://content.time.com/time/arts/article/0,8599,2033166,00.html.

-   How to Lose a Guy in 10 Days. Directed by Donald Petrie, performances by Kate Hudson and Matthew McConaughey, Paramount Pictures, 2003.

-   It Happened One Night. Directed by Frank Capra, Columbia Pictures, 1934.

-   Long Shot. Directed by Jonathan Levine, performances by Seth Rogen and Charlize Theron, Lionsgate, 2019.

-   Magnusson, Kendra. "Tangled." Marvels & Tales, vol. 26, no. 2, 2012, pp. 296-298, 301. ProQuest, http://proxygw.wrlc.org/login?url=https://www.proquest.com/scholarly-journals/tangled/docview/1076735614/se-2.

-   Martin, Karin A., and Emily Kazyak. "Hetero-Romantic Love and Heterosexiness in Children's G-Rated Films." Gender & Society, vol. 23, no. 3, 2009, pp. 315-336. EBSCOhost, https://doi.org/10.1177/0891243209335635.

-   McCarthy, Todd. "'Tangled' -- Film Review." The Hollywood Reporter, 20 Nov. 2012, https://www.hollywoodreporter.com/movies/movie-reviews/tangled-film-review-42752/.

-   McDonald, Tamar Jeffers. Romantic Comedy: Boy Meets Girl Meets Genre. Wallflower, 2007, http://proxygw.wrlc.org/login?url=https://search.ebscohost.com/login.aspx?direct=true&db=nlebk&AN=490816&site=ehost-live&ebv=EB&ppid=pp_Cover.

-   Monster-in-Law. Directed by Robert Luketic, Warner Brothers Pictures, 2005.

-   Mortimer, Claire. Romantic Comedy. Routledge, 2010, https://ebookcentral.proquest.com/lib/gwu/detail.action?docID=496367.

-   Scott, A. O. "Back to the Castle, Where It's All About the Hair." The New York Times, 23 Nov. 2010, https://www.nytimes.com/2010/11/24/movies/24tangled.html.

-   She's All That. Directed by Robert Iscove, Miramax Films, 1999.

-   Siede, Caroline. "10 Years Ago, Tangled Reinvigorated the Disney Princess Tradition." The A.V. Club, 20 Nov. 2020, https://www.avclub.com/years-before-elsa-and-anna-tangled-reinvigorated-the-d-1845661331.

-   Stephens, Jena. "Disney's Darlings: An Analysis of The Princess and the Frog, Tangled, Brave and The Changing Characterization of the Princess Archetype." Interdisciplinary Humanities, vol. 31, no. 3, 2014, pp. 95-107. EBSCOhost, search.ebscohost.com/login.aspx?direct=true&db=a9h&AN=101481692&site=ehost-live.

-   Sultan, Rana S. and Farid Bin Masood. "Portrayals of Love, Romance & Sexuality in Animated Films for Children: A Content Analysis of Animated Films Released in 2018." Journal of Mass Communication Department, vol. 23, no. 1, 2020, pp. 1-11. Dept. of Mass Communication, University of Karachi, http://jmcd-uok.com/index.php/jmcd/article/view/113.

-   "Tangled." CinemaScore, https://www.cinemascore.com.

-   Tangled. Directed by Nathan Greno and Byron Howard, performances by Mandy Moore and Zachary Levi, Walt Disney Studios Motion Pictures, 2010.

-   "Tangled." Metacritic, 24 Nov. 2010, https://www.metacritic.com/movie/tangled.

-   "Tangled." Rotten Tomatoes, https://www.rottentomatoes.com/m/tangled.

-   The Little Mermaid. Directed by Rob Marshall, performance by Halle Bailey, Walt Disney Studios Motion Pictures, 1991.

-   Ticket to Paradise. Directed by Ol Parker, performances by Julia Roberts and George Clooney, Universal Pictures, 2022.

-   Turan, Kenneth. "Movie Review: 'Tangled'." Los Angeles Times, 24 Nov. 2010, https://www.latimes.com/entertainment/la-et-et-tangled-20101124-story.html.
